import type { VehicleType, ViewType } from '../types'

export interface VehiclePartDef {
  partId: string
  partName: string
  view: ViewType
}

/** Catálogo de peças clicáveis por tipo de veículo (extraído dos SVGs). */
export const VEHICLE_PARTS_CATALOG: Record<VehicleType, VehiclePartDef[]> = {
  car: [
    { partId: 'car-ll-wheel-front', partName: 'Roda Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'car-ll-wheel-rear', partName: 'Roda Traseira Esquerda', view: 'lateral-left' },
    { partId: 'car-ll-glass-front', partName: 'Vidro Dianteiro Esquerdo', view: 'lateral-left' },
    { partId: 'car-ll-glass-rear', partName: 'Vidro Traseiro Esquerdo', view: 'lateral-left' },
    { partId: 'car-ll-roof', partName: 'Teto', view: 'lateral-left' },
    { partId: 'car-ll-fender-front', partName: 'Para-lama Dianteiro Esquerdo', view: 'lateral-left' },
    { partId: 'car-ll-door-front', partName: 'Porta Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'car-ll-door-rear', partName: 'Porta Traseira Esquerda', view: 'lateral-left' },
    { partId: 'car-ll-fender-rear', partName: 'Para-lama Traseiro Esquerdo', view: 'lateral-left' },
    { partId: 'car-ll-sill', partName: 'Soleira Esquerda', view: 'lateral-left' },
    { partId: 'car-ll-mirror', partName: 'Retrovisor Esquerdo', view: 'lateral-left' },
    { partId: 'car-rr-wheel-rear', partName: 'Roda Traseira Direita', view: 'lateral-right' },
    { partId: 'car-rr-wheel-front', partName: 'Roda Dianteira Direita', view: 'lateral-right' },
    { partId: 'car-lr-glass-front', partName: 'Vidro Dianteiro Direito', view: 'lateral-right' },
    { partId: 'car-lr-glass-rear', partName: 'Vidro Traseiro Direito', view: 'lateral-right' },
    { partId: 'car-lr-roof', partName: 'Teto', view: 'lateral-right' },
    { partId: 'car-lr-fender-rear', partName: 'Para-lama Traseiro Direito', view: 'lateral-right' },
    { partId: 'car-lr-door-rear', partName: 'Porta Traseira Direita', view: 'lateral-right' },
    { partId: 'car-lr-door-front', partName: 'Porta Dianteira Direita', view: 'lateral-right' },
    { partId: 'car-lr-fender-front', partName: 'Para-lama Dianteiro Direito', view: 'lateral-right' },
    { partId: 'car-lr-sill', partName: 'Soleira Direita', view: 'lateral-right' },
    { partId: 'car-lr-mirror', partName: 'Retrovisor Direito', view: 'lateral-right' },
    { partId: 'car-f-windshield', partName: 'Parabrisa', view: 'frontal' },
    { partId: 'car-f-hood', partName: 'Capô', view: 'frontal' },
    { partId: 'car-f-headlight-left', partName: 'Farol Esquerdo', view: 'frontal' },
    { partId: 'car-f-headlight-right', partName: 'Farol Direito', view: 'frontal' },
    { partId: 'car-f-grille', partName: 'Grade Dianteira', view: 'frontal' },
    { partId: 'car-f-bumper', partName: 'Para-choque Dianteiro', view: 'frontal' },
    { partId: 'car-f-mirror-left', partName: 'Retrovisor Esquerdo', view: 'frontal' },
    { partId: 'car-f-mirror-right', partName: 'Retrovisor Direito', view: 'frontal' },
    { partId: 'car-r-window', partName: 'Vidro Traseiro', view: 'traseira' },
    { partId: 'car-r-trunk', partName: 'Tampa do Porta-malas', view: 'traseira' },
    { partId: 'car-r-light-left', partName: 'Lanterna Traseira Esquerda', view: 'traseira' },
    { partId: 'car-r-light-right', partName: 'Lanterna Traseira Direita', view: 'traseira' },
    { partId: 'car-r-bumper', partName: 'Para-choque Traseiro', view: 'traseira' },
  ],
  car2d: [
    { partId: 'car2d-ll-wheel-front', partName: 'Roda Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'car2d-ll-wheel-rear', partName: 'Roda Traseira Esquerda', view: 'lateral-left' },
    { partId: 'car2d-ll-glass-front', partName: 'Vidro Dianteiro Esquerdo', view: 'lateral-left' },
    { partId: 'car2d-ll-glass-rear', partName: 'Vidro Traseiro Esquerdo', view: 'lateral-left' },
    { partId: 'car2d-ll-roof', partName: 'Teto', view: 'lateral-left' },
    { partId: 'car2d-ll-fender-front', partName: 'Para-lama Dianteiro Esquerdo', view: 'lateral-left' },
    { partId: 'car2d-ll-door', partName: 'Porta Esquerda', view: 'lateral-left' },
    { partId: 'car2d-ll-fender-rear', partName: 'Para-lama Traseiro Esquerdo', view: 'lateral-left' },
    { partId: 'car2d-ll-sill', partName: 'Soleira Esquerda', view: 'lateral-left' },
    { partId: 'car2d-ll-mirror', partName: 'Retrovisor Esquerdo', view: 'lateral-left' },
    { partId: 'car2d-lr-wheel-front', partName: 'Roda Dianteira Direita', view: 'lateral-right' },
    { partId: 'car2d-lr-wheel-rear', partName: 'Roda Traseira Direita', view: 'lateral-right' },
    { partId: 'car2d-lr-glass-front', partName: 'Vidro Dianteiro Direito', view: 'lateral-right' },
    { partId: 'car2d-lr-glass-rear', partName: 'Vidro Traseiro Direito', view: 'lateral-right' },
    { partId: 'car2d-lr-roof', partName: 'Teto', view: 'lateral-right' },
    { partId: 'car2d-lr-door', partName: 'Porta Direita', view: 'lateral-right' },
    { partId: 'car2d-lr-fender-rear', partName: 'Para-lama Traseiro Direito', view: 'lateral-right' },
    { partId: 'car2d-lr-fender-front', partName: 'Para-lama Dianteiro Direito', view: 'lateral-right' },
    { partId: 'car2d-lr-sill', partName: 'Soleira Direita', view: 'lateral-right' },
    { partId: 'car2d-lr-mirror', partName: 'Retrovisor Direito', view: 'lateral-right' },
    { partId: 'car-f-windshield', partName: 'Parabrisa', view: 'frontal' },
    { partId: 'car-f-hood', partName: 'Capô', view: 'frontal' },
    { partId: 'car-f-headlight-left', partName: 'Farol Esquerdo', view: 'frontal' },
    { partId: 'car-f-headlight-right', partName: 'Farol Direito', view: 'frontal' },
    { partId: 'car-f-grille', partName: 'Grade Dianteira', view: 'frontal' },
    { partId: 'car-f-bumper', partName: 'Para-choque Dianteiro', view: 'frontal' },
    { partId: 'car-f-mirror-left', partName: 'Retrovisor Esquerdo', view: 'frontal' },
    { partId: 'car-f-mirror-right', partName: 'Retrovisor Direito', view: 'frontal' },
    { partId: 'car-r-window', partName: 'Vidro Traseiro', view: 'traseira' },
    { partId: 'car-r-trunk', partName: 'Tampa do Porta-malas', view: 'traseira' },
    { partId: 'car-r-light-left', partName: 'Lanterna Traseira Esquerda', view: 'traseira' },
    { partId: 'car-r-light-right', partName: 'Lanterna Traseira Direita', view: 'traseira' },
    { partId: 'car-r-bumper', partName: 'Para-choque Traseiro', view: 'traseira' },
  ],
  moto: [
    { partId: 'moto-ll-wheel-rear', partName: 'Roda Traseira', view: 'lateral-left' },
    { partId: 'moto-ll-wheel-front', partName: 'Roda Dianteira', view: 'lateral-left' },
    { partId: 'moto-ll-handlebars', partName: 'Guidão', view: 'lateral-left' },
    { partId: 'moto-ll-mirror', partName: 'Espelho Retrovisor Esquerdo', view: 'lateral-left' },
    { partId: 'moto-ll-engine', partName: 'Tampa do Motor Esquerda', view: 'lateral-left' },
    { partId: 'moto-ll-fairing', partName: 'Carenagem Lateral Esquerda', view: 'lateral-left' },
    { partId: 'moto-ll-fuel-tank', partName: 'Tanque de Combustível', view: 'lateral-left' },
    { partId: 'moto-ll-seat', partName: 'Assento', view: 'lateral-left' },
    { partId: 'moto-ll-exhaust', partName: 'Escapamento', view: 'lateral-left' },
    { partId: 'moto-ll-fender-front', partName: 'Para-lama Dianteiro', view: 'lateral-left' },
    { partId: 'moto-rr-wheel-front', partName: 'Roda Dianteira', view: 'lateral-right' },
    { partId: 'moto-lr-handlebars', partName: 'Guidão', view: 'lateral-right' },
    { partId: 'moto-lr-mirror', partName: 'Espelho Retrovisor Direito', view: 'lateral-right' },
    { partId: 'moto-rr-wheel-rear', partName: 'Roda Traseira', view: 'lateral-right' },
    { partId: 'moto-lr-engine', partName: 'Tampa do Motor Direita', view: 'lateral-right' },
    { partId: 'moto-lr-fairing', partName: 'Carenagem Lateral Direita', view: 'lateral-right' },
    { partId: 'moto-lr-fuel-tank', partName: 'Tanque de Combustível', view: 'lateral-right' },
    { partId: 'moto-lr-seat', partName: 'Assento', view: 'lateral-right' },
    { partId: 'moto-lr-exhaust', partName: 'Escapamento Principal', view: 'lateral-right' },
    { partId: 'moto-lr-fender-front', partName: 'Para-lama Dianteiro', view: 'lateral-right' },
    { partId: 'moto-f-handlebars', partName: 'Guidão Dianteiro', view: 'frontal' },
    { partId: 'moto-f-headlight', partName: 'Farol Dianteiro', view: 'frontal' },
    { partId: 'moto-f-turn-left', partName: 'Sinalizador Dianteiro Esquerdo', view: 'frontal' },
    { partId: 'moto-f-turn-right', partName: 'Sinalizador Dianteiro Direito', view: 'frontal' },
    { partId: 'moto-f-fender', partName: 'Para-lama Frontal', view: 'frontal' },
    { partId: 'moto-f-forks', partName: 'Garfo / Amortecedores', view: 'frontal' },
    { partId: 'moto-ff-wheel', partName: 'Roda Dianteira', view: 'frontal' },
    { partId: 'moto-r-seat', partName: 'Perfil Traseiro Assento', view: 'traseira' },
    { partId: 'moto-r-light', partName: 'Lanterna Traseira', view: 'traseira' },
    { partId: 'moto-r-turn-left', partName: 'Sinalizador Traseiro Esquerdo', view: 'traseira' },
    { partId: 'moto-r-turn-right', partName: 'Sinalizador Traseiro Direito', view: 'traseira' },
    { partId: 'moto-r-fender', partName: 'Para-lama Traseiro', view: 'traseira' },
    { partId: 'moto-r-plate', partName: 'Placa', view: 'traseira' },
    { partId: 'moto-bb-wheel', partName: 'Roda Traseira', view: 'traseira' },
  ],
  truck: [
    { partId: 'truck-ll-wheel-front', partName: 'Roda Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'truck-ll-wheel-rear-1', partName: 'Roda Traseira Esquerda (Tração)', view: 'lateral-left' },
    { partId: 'truck-ll-wheel-rear-2', partName: 'Roda Traseira Esquerda (Auxiliar)', view: 'lateral-left' },
    { partId: 'truck-ll-cabin', partName: 'Cabine do Caminhão', view: 'lateral-left' },
    { partId: 'truck-ll-cabin-door', partName: 'Porta da Cabine', view: 'lateral-left' },
    { partId: 'truck-ll-cabin-glass', partName: 'Vidro Lateral da Cabine', view: 'lateral-left' },
    { partId: 'truck-ll-cargo-box', partName: 'Baú de Carga', view: 'lateral-left' },
    { partId: 'truck-ll-fuel-tank', partName: 'Tanque de Alumínio', view: 'lateral-left' },
    { partId: 'truck-ll-mirror', partName: 'Retrovisor de Caminhão', view: 'lateral-left' },
    { partId: 'truck-rr-wheel-rear-2', partName: 'Roda Traseira Direita (Auxiliar)', view: 'lateral-right' },
    { partId: 'truck-rr-wheel-rear-1', partName: 'Roda Traseira Direita (Tração)', view: 'lateral-right' },
    { partId: 'truck-rr-wheel-front', partName: 'Roda Dianteira Direita', view: 'lateral-right' },
    { partId: 'truck-lr-cabin', partName: 'Cabine do Caminhão', view: 'lateral-right' },
    { partId: 'truck-lr-cabin-door', partName: 'Porta da Cabine', view: 'lateral-right' },
    { partId: 'truck-lr-cabin-glass', partName: 'Vidro Lateral da Cabine', view: 'lateral-right' },
    { partId: 'truck-lr-cargo-box', partName: 'Baú de Carga', view: 'lateral-right' },
    { partId: 'truck-lr-fuel-tank', partName: 'Tanque de Alumínio', view: 'lateral-right' },
    { partId: 'truck-lr-mirror', partName: 'Retrovisor de Caminhão', view: 'lateral-right' },
    { partId: 'truck-f-deflector', partName: 'Defletor Superior / Teto', view: 'frontal' },
    { partId: 'truck-f-windshield', partName: 'Parabrisa Dianteiro', view: 'frontal' },
    { partId: 'truck-f-grille', partName: 'Grade Frontal Principal', view: 'frontal' },
    { partId: 'truck-f-light-left', partName: 'Farol Dianteiro Esquerdo', view: 'frontal' },
    { partId: 'truck-f-light-right', partName: 'Farol Dianteiro Direito', view: 'frontal' },
    { partId: 'truck-f-mirror-left', partName: 'Retrovisor Principal Esquerdo', view: 'frontal' },
    { partId: 'truck-f-mirror-right', partName: 'Retrovisor Principal Direito', view: 'frontal' },
    { partId: 'truck-f-bumper', partName: 'Para-choque Dianteiro', view: 'frontal' },
    { partId: 'truck-r-box-frame', partName: 'Portas do Baú / Traseira', view: 'traseira' },
    { partId: 'truck-r-bumper', partName: 'Para-choque Traseiro', view: 'traseira' },
    { partId: 'truck-r-light-left', partName: 'Lanterna Traseira Esquerda', view: 'traseira' },
    { partId: 'truck-r-light-right', partName: 'Lanterna Traseira Direita', view: 'traseira' },
  ],
  van: [
    { partId: 'van-ll-roof', partName: 'Teto da Van', view: 'lateral-left' },
    { partId: 'van-ll-panel-side', partName: 'Painel Lateral de Carga', view: 'lateral-left' },
    { partId: 'van-ll-fender-rear', partName: 'Para-lama Traseiro', view: 'lateral-left' },
    { partId: 'van-ll-door-front', partName: 'Porta Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'van-ll-fender-front', partName: 'Para-lama Dianteiro', view: 'lateral-left' },
    { partId: 'van-ll-sill', partName: 'Soleira da Van', view: 'lateral-left' },
    { partId: 'van-ll-wheel-front', partName: 'Roda Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'van-ll-wheel-rear', partName: 'Roda Traseira Esquerda', view: 'lateral-left' },
    { partId: 'van-ll-glass-side', partName: 'Vidro da Porta', view: 'lateral-left' },
    { partId: 'van-ll-glass-front', partName: 'Vidro Dianteiro', view: 'lateral-left' },
    { partId: 'van-ll-mirror', partName: 'Retrovisor Esquerdo', view: 'lateral-left' },
    { partId: 'van-lr-roof', partName: 'Teto da Van', view: 'lateral-right' },
    { partId: 'van-lr-panel-side', partName: 'Painel Lateral de Carga', view: 'lateral-right' },
    { partId: 'van-lr-fender-rear', partName: 'Para-lama Traseiro', view: 'lateral-right' },
    { partId: 'van-lr-door-front', partName: 'Porta Dianteira Direita', view: 'lateral-right' },
    { partId: 'van-lr-fender-front', partName: 'Para-lama Dianteiro', view: 'lateral-right' },
    { partId: 'van-lr-sill', partName: 'Soleira da Van', view: 'lateral-right' },
    { partId: 'van-rr-wheel-front', partName: 'Roda Dianteira Direita', view: 'lateral-right' },
    { partId: 'van-rr-wheel-rear', partName: 'Roda Traseira Direita', view: 'lateral-right' },
    { partId: 'van-lr-glass-side', partName: 'Vidro da Porta', view: 'lateral-right' },
    { partId: 'van-lr-glass-front', partName: 'Vidro Dianteiro', view: 'lateral-right' },
    { partId: 'van-lr-mirror', partName: 'Retrovisor Direito', view: 'lateral-right' },
    { partId: 'van-f-windshield', partName: 'Parabrisa', view: 'frontal' },
    { partId: 'van-f-hood', partName: 'Grade Capô', view: 'frontal' },
    { partId: 'van-f-grille', partName: 'Grade Dianteira', view: 'frontal' },
    { partId: 'van-f-light-left', partName: 'Farol Esquerdo', view: 'frontal' },
    { partId: 'van-f-light-right', partName: 'Farol Direito', view: 'frontal' },
    { partId: 'van-f-bumper', partName: 'Para-choque Dianteiro', view: 'frontal' },
    { partId: 'van-r-body', partName: 'Portas Traseiras / Lataria', view: 'traseira' },
    { partId: 'van-r-window-left', partName: 'Vidro Traseiro Esquerdo', view: 'traseira' },
    { partId: 'van-r-window-right', partName: 'Vidro Traseiro Direito', view: 'traseira' },
    { partId: 'van-r-light-left', partName: 'Lanterna Traseira Esquerda', view: 'traseira' },
    { partId: 'van-r-light-right', partName: 'Lanterna Traseira Direita', view: 'traseira' },
    { partId: 'van-r-bumper', partName: 'Para-choque Traseiro', view: 'traseira' },
  ],
  bus: [
    { partId: 'bus-ll-wheel-front', partName: 'Roda Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'bus-ll-wheel-rear-1', partName: 'Roda Traseira Esquerda (Tração)', view: 'lateral-left' },
    { partId: 'bus-ll-wheel-rear-2', partName: 'Roda Traseira Esquerda (Auxiliar)', view: 'lateral-left' },
    { partId: 'bus-ll-body', partName: 'Carroceria / Lateral', view: 'lateral-left' },
    { partId: 'bus-ll-windows', partName: 'Janelas dos Passageiros', view: 'lateral-left' },
    { partId: 'bus-ll-windshield', partName: 'Parabrisa Dianteiro (Lateral)', view: 'lateral-left' },
    { partId: 'bus-ll-door', partName: 'Porta de Passageiros', view: 'lateral-left' },
    { partId: 'bus-ll-luggage', partName: 'Bagageiro / Portas de Carga', view: 'lateral-left' },
    { partId: 'bus-rr-wheel-front', partName: 'Roda Dianteira Direita', view: 'lateral-right' },
    { partId: 'bus-rr-wheel-rear-1', partName: 'Roda Traseira Direita (Tração)', view: 'lateral-right' },
    { partId: 'bus-rr-wheel-rear-2', partName: 'Roda Traseira Direita (Auxiliar)', view: 'lateral-right' },
    { partId: 'bus-lr-body', partName: 'Carroceria / Lateral', view: 'lateral-right' },
    { partId: 'bus-lr-windows', partName: 'Janelas dos Passageiros', view: 'lateral-right' },
    { partId: 'bus-lr-windshield', partName: 'Parabrisa Dianteiro (Lateral)', view: 'lateral-right' },
    { partId: 'bus-lr-door', partName: 'Porta de Passageiros', view: 'lateral-right' },
    { partId: 'bus-lr-luggage', partName: 'Bagageiro / Portas de Carga', view: 'lateral-right' },
    { partId: 'bus-f-body', partName: 'Painel Frontal', view: 'frontal' },
    { partId: 'bus-f-itinerary', partName: 'Painel de Itinerário', view: 'frontal' },
    { partId: 'bus-f-windshield', partName: 'Parabrisa Dianteiro Panorâmico', view: 'frontal' },
    { partId: 'bus-f-light-left', partName: 'Farol Dianteiro Esquerdo', view: 'frontal' },
    { partId: 'bus-f-light-right', partName: 'Farol Dianteiro Direito', view: 'frontal' },
    { partId: 'bus-f-bumper', partName: 'Para-choque Dianteiro', view: 'frontal' },
    { partId: 'bus-f-mirror-left', partName: 'Retrovisor Esquerdo', view: 'frontal' },
    { partId: 'bus-f-mirror-right', partName: 'Retrovisor Direito', view: 'frontal' },
    { partId: 'bus-r-body', partName: 'Painel Traseiro', view: 'traseira' },
    { partId: 'bus-r-window', partName: 'Vidro Traseiro', view: 'traseira' },
    { partId: 'bus-r-engine-cover', partName: 'Tampa do Motor / Grade', view: 'traseira' },
    { partId: 'bus-r-light-left', partName: 'Lanterna Traseira Esquerda', view: 'traseira' },
    { partId: 'bus-r-light-right', partName: 'Lanterna Traseira Direita', view: 'traseira' },
    { partId: 'bus-r-bumper', partName: 'Para-choque Traseiro', view: 'traseira' },
  ],
  microbus: [
    { partId: 'microbus-l-wheel-rear', partName: 'Roda Traseira Esquerda', view: 'lateral-left' },
    { partId: 'microbus-l-wheel-front', partName: 'Roda Dianteira Esquerda', view: 'lateral-left' },
    { partId: 'microbus-l-body', partName: 'Carroceria / Lateral', view: 'lateral-left' },
    { partId: 'microbus-l-windows', partName: 'Janelas dos Passageiros', view: 'lateral-left' },
    { partId: 'microbus-l-windshield', partName: 'Parabrisa Dianteiro (Lateral)', view: 'lateral-left' },
    { partId: 'microbus-l-door', partName: 'Porta de Passageiros', view: 'lateral-left' },
    { partId: 'microbus-r-wheel-rear', partName: 'Roda Traseira Direita', view: 'lateral-right' },
    { partId: 'microbus-r-wheel-front', partName: 'Roda Dianteira Direita', view: 'lateral-right' },
    { partId: 'microbus-r-body', partName: 'Carroceria / Lateral', view: 'lateral-right' },
    { partId: 'microbus-r-windows', partName: 'Janelas dos Passageiros', view: 'lateral-right' },
    { partId: 'microbus-r-windshield', partName: 'Parabrisa Dianteiro (Lateral)', view: 'lateral-right' },
    { partId: 'microbus-r-door', partName: 'Porta de Passageiros', view: 'lateral-right' },
    { partId: 'microbus-f-body', partName: 'Painel Frontal', view: 'frontal' },
    { partId: 'microbus-f-itinerary', partName: 'Painel de Itinerário', view: 'frontal' },
    { partId: 'microbus-f-windshield', partName: 'Parabrisa Dianteiro', view: 'frontal' },
    { partId: 'microbus-f-light-left', partName: 'Farol Dianteiro Esquerdo', view: 'frontal' },
    { partId: 'microbus-f-light-right', partName: 'Farol Dianteiro Direito', view: 'frontal' },
    { partId: 'microbus-f-bumper', partName: 'Para-choque Dianteiro', view: 'frontal' },
    { partId: 'microbus-f-mirror-left', partName: 'Retrovisor Esquerdo', view: 'frontal' },
    { partId: 'microbus-f-mirror-right', partName: 'Retrovisor Direito', view: 'frontal' },
    { partId: 'microbus-t-body', partName: 'Painel Traseiro', view: 'traseira' },
    { partId: 'microbus-t-window', partName: 'Vidro Traseiro', view: 'traseira' },
    { partId: 'microbus-t-engine-cover', partName: 'Tampa do Motor / Grade', view: 'traseira' },
    { partId: 'microbus-t-light-left', partName: 'Lanterna Traseira Esquerda', view: 'traseira' },
    { partId: 'microbus-t-light-right', partName: 'Lanterna Traseira Direita', view: 'traseira' },
    { partId: 'microbus-t-bumper', partName: 'Para-choque Traseiro', view: 'traseira' },
  ],
  custom: [
    { partId: 'cust-ll-roof', partName: 'Teto / Parte Superior', view: 'lateral-left' },
    { partId: 'cust-ll-windows', partName: 'Lateral Superior (Área de Vidro)', view: 'lateral-left' },
    { partId: 'cust-ll-body-front', partName: 'Lateral Dianteira', view: 'lateral-left' },
    { partId: 'cust-ll-body-rear', partName: 'Lateral Traseira', view: 'lateral-left' },
    { partId: 'cust-ll-sill', partName: 'Saia / Parte Inferior', view: 'lateral-left' },
    { partId: 'cust-lr-roof', partName: 'Teto / Parte Superior', view: 'lateral-right' },
    { partId: 'cust-lr-windows', partName: 'Lateral Superior (Área de Vidro)', view: 'lateral-right' },
    { partId: 'cust-lr-body-front', partName: 'Lateral Dianteira', view: 'lateral-right' },
    { partId: 'cust-lr-body-rear', partName: 'Lateral Traseira', view: 'lateral-right' },
    { partId: 'cust-lr-sill', partName: 'Saia / Parte Inferior', view: 'lateral-right' },
    { partId: 'cust-f-glass', partName: 'Vidro Frontal / Parabrisa', view: 'frontal' },
    { partId: 'cust-f-top', partName: 'Frente Superior', view: 'frontal' },
    { partId: 'cust-f-grille', partName: 'Grade / Para-choque', view: 'frontal' },
    { partId: 'cust-f-light-left', partName: 'Farol Esquerdo', view: 'frontal' },
    { partId: 'cust-f-light-right', partName: 'Farol Direito', view: 'frontal' },
    { partId: 'cust-r-glass', partName: 'Vidro Traseiro', view: 'traseira' },
    { partId: 'cust-r-top', partName: 'Traseira Superior', view: 'traseira' },
    { partId: 'cust-r-bottom', partName: 'Traseira Inferior', view: 'traseira' },
    { partId: 'cust-r-light-left', partName: 'Lanterna Esquerda', view: 'traseira' },
    { partId: 'cust-r-light-right', partName: 'Lanterna Direita', view: 'traseira' },
  ],
}

export function getPartsForVehicle(vehicleType: VehicleType): VehiclePartDef[] {
  return VEHICLE_PARTS_CATALOG[vehicleType] ?? []
}

export function findPartById(vehicleType: VehicleType, partId: string): VehiclePartDef | undefined {
  return getPartsForVehicle(vehicleType).find(p => p.partId === partId)
}

/** Lista compacta para o prompt da IA. */
export function formatPartsCatalogForPrompt(vehicleType: VehicleType): string {
  return getPartsForVehicle(vehicleType)
    .map(p => `${p.partId}|${p.view}|${p.partName}`)
    .join('\n')
}
